package com.flashpool.ui.theme

import androidx.compose.ui.graphics.Color

/** Stitch DESIGN.md tokens — High-Velocity Marketplace */
object FlashPoolTokens {
    object Light {
        val primary = Color(0xFFB4252D)
        val onPrimary = Color(0xFFFFFFFF)
        val primaryContainer = Color(0xFFFF5C5C)
        val onPrimaryContainer = Color(0xFF62000C)
        val secondary = Color(0xFF03696A)
        val onSecondary = Color(0xFFFFFFFF)
        val secondaryContainer = Color(0xFF9EEDED)
        val onSecondaryContainer = Color(0xFF0F6E6E)
        val tertiary = Color(0xFF006C4F)
        val onTertiary = Color(0xFFFFFFFF)
        val tertiaryContainer = Color(0xFF00A97D)
        val onTertiaryContainer = Color(0xFF003525)
        val error = Color(0xFFBA1A1A)
        val onError = Color(0xFFFFFFFF)
        val errorContainer = Color(0xFFFFDAD6)
        val onErrorContainer = Color(0xFF93000A)
        val background = Color(0xFFF9F9FF)
        val onBackground = Color(0xFF0D1C32)
        val surface = Color(0xFFF9F9FF)
        val onSurface = Color(0xFF0D1C32)
        val surfaceVariant = Color(0xFFD6E3FF)
        val onSurfaceVariant = Color(0xFF5A403F)
        val outline = Color(0xFF8E706E)
        val outlineVariant = Color(0xFFE2BEBC)
        val surfaceContainerLowest = Color(0xFFFFFFFF)
        val surfaceContainerLow = Color(0xFFF0F3FF)
        val surfaceContainer = Color(0xFFE8EEFF)
        val surfaceContainerHigh = Color(0xFFDFE8FF)
        val surfaceContainerHighest = Color(0xFFD6E3FF)
        val inverseSurface = Color(0xFF233148)
        val inverseOnSurface = Color(0xFFECF0FF)
        val inversePrimary = Color(0xFFFFB3AF)
        val countdownBlock = Color(0xFF0D1C32)
        val onCountdownBlock = Color(0xFFFFFFFF)
        val ticketSurface = Color(0xFFFFFFFF)
        val bannerOverlay = Color(0xFF8B1A22)
    }

    object Dark {
        val primary = Color(0xFFFF5C5C)
        val onPrimary = Color(0xFF410005)
        val primaryContainer = Color(0xFFB4252D)
        val onPrimaryContainer = Color(0xFFFFDAD7)
        val secondary = Color(0xFF85D4D3)
        val onSecondary = Color(0xFF003738)
        val secondaryContainer = Color(0xFF03696A)
        val onSecondaryContainer = Color(0xFF9EEDED)
        val tertiary = Color(0xFF59DDAD)
        val onTertiary = Color(0xFF003825)
        val tertiaryContainer = Color(0xFF00513A)
        val onTertiaryContainer = Color(0xFF78FAC8)
        val error = Color(0xFFFFB4AB)
        val onError = Color(0xFF690005)
        val errorContainer = Color(0xFF93000A)
        val onErrorContainer = Color(0xFFFFDAD6)
        val background = Color(0xFF0A192F)
        val onBackground = Color(0xFFECF0FF)
        val surface = Color(0xFF0A192F)
        val onSurface = Color(0xFFFFFFFF)
        val surfaceVariant = Color(0xFF1E3354)
        val onSurfaceVariant = Color(0xFFB8C4DC)
        val outline = Color(0xFF5A6B85)
        val outlineVariant = Color(0xFF2A3F5C)
        val surfaceContainerLowest = Color(0xFF0D1F38)
        val surfaceContainerLow = Color(0xFF132238)
        val surfaceContainer = Color(0xFF1A2A45)
        val surfaceContainerHigh = Color(0xFF223352)
        val surfaceContainerHighest = Color(0xFF2A3D5E)
        val inverseSurface = Color(0xFFECF0FF)
        val inverseOnSurface = Color(0xFF233148)
        val inversePrimary = Color(0xFFB4252D)
        val countdownBlock = Color(0xFF0A192F)
        val onCountdownBlock = Color(0xFFFFFFFF)
        val ticketSurface = Color(0xFF132238)
        val bannerOverlay = Color(0xFF6B151C)
    }
}
